"""create saved media tables

Revision ID: 8e6b3cd149da
Revises: 6b3a99cd5fde
Create Date: 2026-07-27 11:14:50.887329
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "8e6b3cd149da"
down_revision: str | Sequence[str] | None = "6b3a99cd5fde"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saved_brolls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "provider",
            sa.String(length=32),
            server_default=sa.text("'pexels'"),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("preview_url", sa.String(length=2048), nullable=True),
        sa.Column("thumbnail_url", sa.String(length=2048), nullable=True),
        sa.Column("creator_name", sa.String(length=500), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=5000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "provider",
            "external_id",
            name="uq_saved_brolls_project_provider_external_id",
        ),
    )
    with op.batch_alter_table("saved_brolls", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_saved_brolls_project_id"),
            ["project_id"],
            unique=False,
        )

    op.create_table(
        "saved_references",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "provider",
            sa.String(length=32),
            server_default=sa.text("'youtube'"),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("thumbnail_url", sa.String(length=2048), nullable=True),
        sa.Column("channel_title", sa.String(length=500), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.String(length=5000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "provider",
            "external_id",
            name="uq_saved_references_project_provider_external_id",
        ),
    )
    with op.batch_alter_table("saved_references", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_saved_references_project_id"),
            ["project_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("saved_references", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_saved_references_project_id"))

    op.drop_table("saved_references")
    with op.batch_alter_table("saved_brolls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_saved_brolls_project_id"))

    op.drop_table("saved_brolls")
    # ### end Alembic commands ###
